/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateThuongArgs } from "./CreateThuongArgs";
import { UpdateThuongArgs } from "./UpdateThuongArgs";
import { DeleteThuongArgs } from "./DeleteThuongArgs";
import { ThuongFindManyArgs } from "./ThuongFindManyArgs";
import { ThuongFindUniqueArgs } from "./ThuongFindUniqueArgs";
import { Thuong } from "./Thuong";
import { ThuongService } from "../thuong.service";

@graphql.Resolver(() => Thuong)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ThuongResolverBase {
  constructor(
    protected readonly service: ThuongService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Thuong",
    action: "read",
    possession: "any",
  })
  async _thuongsMeta(
    @graphql.Args() args: ThuongFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Thuong])
  @nestAccessControl.UseRoles({
    resource: "Thuong",
    action: "read",
    possession: "any",
  })
  async thuongs(@graphql.Args() args: ThuongFindManyArgs): Promise<Thuong[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Thuong, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Thuong",
    action: "read",
    possession: "own",
  })
  async thuong(
    @graphql.Args() args: ThuongFindUniqueArgs
  ): Promise<Thuong | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Thuong)
  @nestAccessControl.UseRoles({
    resource: "Thuong",
    action: "create",
    possession: "any",
  })
  async createThuong(@graphql.Args() args: CreateThuongArgs): Promise<Thuong> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Thuong)
  @nestAccessControl.UseRoles({
    resource: "Thuong",
    action: "update",
    possession: "any",
  })
  async updateThuong(
    @graphql.Args() args: UpdateThuongArgs
  ): Promise<Thuong | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Thuong)
  @nestAccessControl.UseRoles({
    resource: "Thuong",
    action: "delete",
    possession: "any",
  })
  async deleteThuong(
    @graphql.Args() args: DeleteThuongArgs
  ): Promise<Thuong | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
